import { PrismaClient, Category, Difficulty, BadgeRarity } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Comenzando seed de la base de datos...');

  // Limpiar datos existentes
  await prisma.visit.deleteMany();
  await prisma.userBadge.deleteMany();
  await prisma.badge.deleteMany();
  await prisma.pOI.deleteMany();
  console.log('✓ Datos antiguos eliminados');

  // Crear POIs de Estepona
  const pois = [
    {
      nfcUid: 'NFC001TORRE',
      slug: 'torre-del-reloj',
      category: Category.MONUMENT,
      lat: 36.4265,
      lng: -5.1469,
      address: 'Plaza del Reloj, Estepona',
      nameEs: 'Torre del Reloj',
      nameEn: 'Clock Tower',
      nameFr: 'Tour de l\'Horloge',
      nameDe: 'Uhrturm',
      nameIt: 'Torre dell\'Orologio',
      descEs: 'La emblemática Torre del Reloj es uno de los símbolos más reconocibles de Estepona. Construida en el siglo XV, esta torre de origen defensivo formaba parte de las antiguas murallas de la villa.',
      descEn: 'The emblematic Clock Tower is one of the most recognizable symbols of Estepona. Built in the 15th century, this tower of defensive origin was part of the old town walls.',
      descFr: 'La Tour de l\'Horloge emblématique est l\'un des symboles les plus reconnaissables d\'Estepona. Construite au XVe siècle, cette tour d\'origine défensive faisait partie des anciens remparts de la ville.',
      descDe: 'Der emblematische Uhrturm ist eines der bekanntesten Wahrzeichen von Estepona. Der im 15. Jahrhundert erbaute Turm war Teil der alten Stadtmauern.',
      descIt: 'L\'emblematica Torre dell\'Orologio è uno dei simboli più riconoscibili di Estepona. Costruita nel XV secolo, questa torre di origine difensiva faceva parte delle antiche mura della città.',
      images: [],
      points: 15,
      xpReward: 75,
      premiumOnly: false,
      difficulty: Difficulty.EASY,
      duration: 15,
    },
    {
      nfcUid: 'NFC002MURALES',
      slug: 'ruta-murales',
      category: Category.CULTURE,
      lat: 36.4278,
      lng: -5.1485,
      address: 'Casco Antiguo, Estepona',
      nameEs: 'Ruta de los Murales',
      nameEn: 'Mural Route',
      nameFr: 'Route des Fresques',
      nameDe: 'Wandgemälde Route',
      nameIt: 'Percorso dei Murales',
      descEs: 'Estepona es conocida como el "Jardín de la Costa del Sol" y sus murales colorean las fachadas del casco antiguo. Más de 60 murales gigantes adornan las paredes del pueblo.',
      descEn: 'Estepona is known as the "Garden of the Costa del Sol" and its murals color the facades of the old town. More than 60 giant murals adorn the village walls.',
      descFr: 'Estepona est connue comme le "Jardin de la Costa del Sol" et ses fresques colorent les façades de la vieille ville. Plus de 60 fresques géantes ornent les murs du village.',
      descDe: 'Estepona ist als "Garten der Costa del Sol" bekannt und seine Wandgemälde färben die Fassaden der Altstadt. Mehr als 60 riesige Wandgemälde schmücken die Dorfmauern.',
      descIt: 'Estepona è conosciuta come il "Giardino della Costa del Sol" e i suoi murales colorano le facciate del centro storico. Più di 60 murales giganti adornano i muri del paese.',
      images: [],
      points: 20,
      xpReward: 100,
      premiumOnly: false,
      difficulty: Difficulty.EASY,
      duration: 30,
    },
    {
      nfcUid: 'NFC003ORQUIDARIO',
      slug: 'orquidario-estepona',
      category: Category.NATURE,
      lat: 36.4290,
      lng: -5.1520,
      address: 'Calle Terraza, 86, Estepona',
      nameEs: 'Orquidario de Estepona',
      nameEn: 'Estepona Orchid House',
      nameFr: 'Orchidarium d\'Estepona',
      nameDe: 'Orchideenhaus Estepona',
      nameIt: 'Orchidario di Estepona',
      descEs: 'El Orquidario de Estepona alberga más de 1.300 especies de orquídeas y una impresionante cúpula de cristal. Una cascada de 15 metros crea un ambiente tropical único.',
      descEn: 'The Estepona Orchid House houses more than 1,300 species of orchids and an impressive glass dome. A 15-meter waterfall creates a unique tropical atmosphere.',
      descFr: 'L\'Orchidarium d\'Estepona abrite plus de 1 300 espèces d\'orchidées et un dôme de verre impressionnant. Une cascade de 15 mètres crée une atmosphère tropicale unique.',
      descDe: 'Das Orchideenhaus Estepona beherbergt mehr als 1.300 Orchideenarten und eine beeindruckende Glaskuppel. Ein 15 Meter hoher Wasserfall schafft eine einzigartige tropische Atmosphäre.',
      descIt: 'L\'Orchidario di Estepona ospita più di 1.300 specie di orchidee e un\'impressionante cupola di vetro. Una cascata di 15 metri crea un\'atmosfera tropicale unica.',
      images: [],
      audioGuideEs: '',
      audioGuideEn: '',
      audioGuideFr: '',
      audioGuideDe: '',
      audioGuideIt: '',
      points: 25,
      xpReward: 120,
      premiumOnly: true,
      difficulty: Difficulty.EASY,
      duration: 45,
    },
    {
      nfcUid: 'NFC004PLAYA',
      slug: 'playa-rada',
      category: Category.BEACH,
      lat: 36.4240,
      lng: -5.1450,
      address: 'Paseo Marítimo, Estepona',
      nameEs: 'Playa de la Rada',
      nameEn: 'La Rada Beach',
      nameFr: 'Plage de la Rada',
      nameDe: 'La Rada Strand',
      nameIt: 'Spiaggia della Rada',
      descEs: 'La playa urbana más importante de Estepona, con más de 2.5 km de arena dorada y aguas cristalinas. Perfecta para disfrutar del sol mediterráneo.',
      descEn: 'The most important urban beach in Estepona, with more than 2.5 km of golden sand and crystal clear waters. Perfect for enjoying the Mediterranean sun.',
      descFr: 'La plage urbaine la plus importante d\'Estepona, avec plus de 2,5 km de sable doré et des eaux cristallines. Parfait pour profiter du soleil méditerranéen.',
      descDe: 'Der wichtigste Stadtstrand von Estepona, mit mehr als 2,5 km goldenem Sand und kristallklarem Wasser. Perfekt, um die mediterrane Sonne zu genießen.',
      descIt: 'La spiaggia urbana più importante di Estepona, con più di 2,5 km di sabbia dorata e acque cristalline. Perfetta per godersi il sole mediterraneo.',
      images: [],
      points: 10,
      xpReward: 50,
      premiumOnly: false,
      difficulty: Difficulty.EASY,
      duration: 60,
    },
    {
      nfcUid: 'NFC005MERCADO',
      slug: 'mercado-gastronomico',
      category: Category.RESTAURANT,
      lat: 36.4272,
      lng: -5.1478,
      address: 'Plaza ABC, Estepona',
      nameEs: 'Mercado Gastronómico',
      nameEn: 'Gastronomic Market',
      nameFr: 'Marché Gastronomique',
      nameDe: 'Gastronomischer Markt',
      nameIt: 'Mercato Gastronomico',
      descEs: 'Un espacio moderno dedicado a la gastronomía local. Descubre los sabores auténticos de la cocina andaluza y malagueña en un ambiente único.',
      descEn: 'A modern space dedicated to local gastronomy. Discover the authentic flavors of Andalusian and Malaga cuisine in a unique atmosphere.',
      descFr: 'Un espace moderne dédié à la gastronomie locale. Découvrez les saveurs authentiques de la cuisine andalouse et malaguène dans une atmosphère unique.',
      descDe: 'Ein moderner Raum der lokalen Gastronomie gewidmet. Entdecken Sie die authentischen Aromen der andalusischen und Malaga-Küche in einzigartiger Atmosphäre.',
      descIt: 'Uno spazio moderno dedicato alla gastronomia locale. Scopri i sapori autentici della cucina andalusa e malaguense in un\'atmosfera unica.',
      images: [],
      points: 15,
      xpReward: 80,
      premiumOnly: false,
      difficulty: Difficulty.EASY,
      duration: 45,
    },
    {
      nfcUid: 'NFC006MIRADOR',
      slug: 'mirador-carmen',
      category: Category.VIEWPOINT,
      lat: 36.4295,
      lng: -5.1455,
      address: 'Calle del Carmen, Estepona',
      nameEs: 'Mirador del Carmen',
      nameEn: 'Carmen Viewpoint',
      nameFr: 'Belvédère du Carmen',
      nameDe: 'Carmen Aussichtspunkt',
      nameIt: 'Belvedere del Carmen',
      descEs: 'Uno de los mejores miradores de Estepona con vistas panorámicas del mar Mediterráneo y la costa africana en días despejados.',
      descEn: 'One of the best viewpoints in Estepona with panoramic views of the Mediterranean Sea and the African coast on clear days.',
      descFr: 'L\'un des meilleurs points de vue d\'Estepona avec des vues panoramiques sur la mer Méditerranée et la côte africaine par temps clair.',
      descDe: 'Einer der besten Aussichtspunkte in Estepona mit Panoramablick auf das Mittelmeer und die afrikanische Küste an klaren Tagen.',
      descIt: 'Uno dei migliori punti panoramici di Estepona con viste panoramiche sul Mar Mediterraneo e sulla costa africana nelle giornate limpide.',
      images: [],
      points: 20,
      xpReward: 90,
      premiumOnly: false,
      difficulty: Difficulty.MEDIUM,
      duration: 20,
    },
    {
      nfcUid: 'NFC007PARQUE',
      slug: 'parque-botanico',
      category: Category.PARK,
      lat: 36.4310,
      lng: -5.1495,
      address: 'Avenida San Lorenzo, Estepona',
      nameEs: 'Parque Botánico-Ornitológico',
      nameEn: 'Botanical and Ornithological Park',
      nameFr: 'Parc Botanique et Ornithologique',
      nameDe: 'Botanischer und Ornithologischer Park',
      nameIt: 'Parco Botanico e Ornitologico',
      descEs: 'Un espacio verde de más de 17.000 m² con especies vegetales de los cinco continentes y una gran variedad de aves exóticas.',
      descEn: 'A green space of more than 17,000 m² with plant species from five continents and a wide variety of exotic birds.',
      descFr: 'Un espace vert de plus de 17 000 m² avec des espèces végétales des cinq continents et une grande variété d\'oiseaux exotiques.',
      descDe: 'Eine Grünfläche von mehr als 17.000 m² mit Pflanzenarten von fünf Kontinenten und einer großen Vielfalt exotischer Vögel.',
      descIt: 'Uno spazio verde di oltre 17.000 m² con specie vegetali dei cinque continenti e una grande varietà di uccelli esotici.',
      images: [],
      points: 15,
      xpReward: 70,
      premiumOnly: false,
      difficulty: Difficulty.EASY,
      duration: 40,
    },
    {
      nfcUid: 'NFC008CASTILLO',
      slug: 'castillo-nicio',
      category: Category.HISTORIC,
      lat: 36.4255,
      lng: -5.1462,
      address: 'Plaza Blas Infante, Estepona',
      nameEs: 'Castillo de San Luis (Restos)',
      nameEn: 'Castle of San Luis (Ruins)',
      nameFr: 'Château de San Luis (Ruines)',
      nameDe: 'Burg San Luis (Ruinen)',
      nameIt: 'Castello di San Luis (Rovine)',
      descEs: 'Restos del antiguo castillo medieval que defendía Estepona. Aunque solo quedan fragmentos, es un testimonio importante de la historia local.',
      descEn: 'Remains of the old medieval castle that defended Estepona. Although only fragments remain, it is an important testimony to local history.',
      descFr: 'Vestiges de l\'ancien château médiéval qui défendait Estepona. Bien que seuls des fragments subsistent, c\'est un témoignage important de l\'histoire locale.',
      descDe: 'Überreste der alten mittelalterlichen Burg, die Estepona verteidigte. Obwohl nur Fragmente übrig sind, ist es ein wichtiges Zeugnis der lokalen Geschichte.',
      descIt: 'Resti dell\'antico castello medievale che difendeva Estepona. Sebbene rimangano solo frammenti, è una testimonianza importante della storia locale.',
      images: [],
      points: 20,
      xpReward: 100,
      premiumOnly: false,
      difficulty: Difficulty.MEDIUM,
      duration: 25,
    },
    {
      nfcUid: 'NFC009MUSEO',
      slug: 'museo-taurino',
      category: Category.MUSEUM,
      lat: 36.4268,
      lng: -5.1473,
      address: 'Plaza de Toros, Estepona',
      nameEs: 'Museo Taurino Antonio Ordóñez',
      nameEn: 'Antonio Ordóñez Bullfighting Museum',
      nameFr: 'Musée Taurin Antonio Ordóñez',
      nameDe: 'Stierkampfmuseum Antonio Ordóñez',
      nameIt: 'Museo Taurino Antonio Ordóñez',
      descEs: 'Museo dedicado al famoso torero Antonio Ordóñez, con una colección de trajes, carteles y objetos relacionados con la tauromaquia.',
      descEn: 'Museum dedicated to the famous bullfighter Antonio Ordóñez, with a collection of costumes, posters and objects related to bullfighting.',
      descFr: 'Musée dédié au célèbre torero Antonio Ordóñez, avec une collection de costumes, d\'affiches et d\'objets liés à la tauromachie.',
      descDe: 'Museum, das dem berühmten Stierkämpfer Antonio Ordóñez gewidmet ist, mit einer Sammlung von Kostümen, Plakaten und Objekten im Zusammenhang mit dem Stierkampf.',
      descIt: 'Museo dedicato al famoso torero Antonio Ordóñez, con una collezione di costumi, manifesti e oggetti legati alla tauromachia.',
      images: [],
      audioGuideEs: '',
      audioGuideEn: '',
      audioGuideFr: '',
      audioGuideDe: '',
      audioGuideIt: '',
      points: 20,
      xpReward: 100,
      premiumOnly: true,
      difficulty: Difficulty.EASY,
      duration: 35,
    },
    {
      nfcUid: 'NFC010PUERTO',
      slug: 'puerto-deportivo',
      category: Category.VIEWPOINT,
      lat: 36.4210,
      lng: -5.1420,
      address: 'Puerto Deportivo de Estepona',
      nameEs: 'Puerto Deportivo',
      nameEn: 'Marina',
      nameFr: 'Port de Plaisance',
      nameDe: 'Yachthafen',
      nameIt: 'Porto Turistico',
      descEs: 'El puerto deportivo de Estepona es un lugar perfecto para pasear, disfrutar de restaurantes con vistas al mar y admirar los yates de lujo.',
      descEn: 'The Estepona marina is a perfect place to stroll, enjoy restaurants overlooking the sea and admire luxury yachts.',
      descFr: 'Le port de plaisance d\'Estepona est un endroit parfait pour se promener, profiter de restaurants avec vue sur la mer et admirer des yachts de luxe.',
      descDe: 'Der Yachthafen von Estepona ist ein perfekter Ort zum Spazierengehen, Genießen von Restaurants mit Meerblick und Bewundern von Luxusyachten.',
      descIt: 'Il porto turistico di Estepona è un luogo perfetto per passeggiare, godersi i ristoranti con vista sul mare e ammirare gli yacht di lusso.',
      images: [],
      points: 15,
      xpReward: 75,
      premiumOnly: false,
      difficulty: Difficulty.EASY,
      duration: 30,
    },
  ];

  console.log('📍 Creando POIs...');
  for (const poi of pois) {
    await prisma.pOI.create({ data: poi });
  }
  console.log(`✓ ${pois.length} POIs creados`);

  // Crear badges
  const badges = [
    {
      slug: 'explorador-novato',
      nameEs: 'Explorador Novato',
      nameEn: 'Novice Explorer',
      nameFr: 'Explorateur Débutant',
      nameDe: 'Anfänger-Entdecker',
      descriptionEs: 'Visita tu primer POI',
      descriptionEn: 'Visit your first POI',
      descriptionFr: 'Visitez votre premier POI',
      descriptionDe: 'Besuchen Sie Ihren ersten POI',
      icon: '🎯',
      category: null,
      rarity: BadgeRarity.COMMON,
      requirement: { type: 'visits_count', value: 1 },
      pointsReward: 10,
      xpReward: 50,
    },
    {
      slug: 'conocedor-local',
      nameEs: 'Conocedor Local',
      nameEn: 'Local Connoisseur',
      nameFr: 'Connaisseur Local',
      nameDe: 'Lokaler Kenner',
      descriptionEs: 'Visita 5 POIs diferentes',
      descriptionEn: 'Visit 5 different POIs',
      descriptionFr: 'Visitez 5 POIs différents',
      descriptionDe: 'Besuchen Sie 5 verschiedene POIs',
      icon: '⭐',
      category: null,
      rarity: BadgeRarity.RARE,
      requirement: { type: 'visits_count', value: 5 },
      pointsReward: 50,
      xpReward: 200,
    },
    {
      slug: 'maestro-turista',
      nameEs: 'Maestro Turista',
      nameEn: 'Master Tourist',
      nameFr: 'Maître Touriste',
      nameDe: 'Meister-Tourist',
      descriptionEs: 'Completa todos los POIs',
      descriptionEn: 'Complete all POIs',
      descriptionFr: 'Complétez tous les POIs',
      descriptionDe: 'Alle POIs abschließen',
      icon: '🏆',
      category: null,
      rarity: BadgeRarity.LEGENDARY,
      requirement: { type: 'visits_count', value: 10 },
      pointsReward: 200,
      xpReward: 1000,
    },
    {
      slug: 'amante-cultura',
      nameEs: 'Amante de la Cultura',
      nameEn: 'Culture Lover',
      nameFr: 'Amateur de Culture',
      nameDe: 'Kulturliebhaber',
      descriptionEs: 'Visita 3 POIs culturales',
      descriptionEn: 'Visit 3 cultural POIs',
      descriptionFr: 'Visitez 3 POIs culturels',
      descriptionDe: 'Besuchen Sie 3 kulturelle POIs',
      icon: '🎭',
      category: Category.CULTURE,
      rarity: BadgeRarity.RARE,
      requirement: { type: 'visits_count', value: 3, category: 'CULTURE' },
      pointsReward: 30,
      xpReward: 150,
    },
    {
      slug: 'amante-naturaleza',
      nameEs: 'Amante de la Naturaleza',
      nameEn: 'Nature Lover',
      nameFr: 'Amateur de Nature',
      nameDe: 'Naturliebhaber',
      descriptionEs: 'Visita todos los POIs de naturaleza',
      descriptionEn: 'Visit all nature POIs',
      descriptionFr: 'Visitez tous les POIs de nature',
      descriptionDe: 'Besuchen Sie alle Natur-POIs',
      icon: '🌿',
      category: Category.NATURE,
      rarity: BadgeRarity.EPIC,
      requirement: { type: 'visits_count', value: 2, category: 'NATURE' },
      pointsReward: 40,
      xpReward: 180,
    },
  ];

  console.log('🏅 Creando badges...');
  for (const badge of badges) {
    await prisma.badge.create({ data: badge });
  }
  console.log(`✓ ${badges.length} badges creados`);

  console.log('✅ Seed completado exitosamente!');
}

main()
  .catch((e) => {
    console.error('❌ Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
